"""Configuration for media file discovery and browser settings"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/media/config.ipynb.

# %% auto 0
__all__ = ['MEDIA_CONFIG_SCHEMA', 'MediaConfig']

# %% ../../nbs/media/config.ipynb 3
from dataclasses import dataclass, field
from typing import List

# %% ../../nbs/media/config.ipynb 5
@dataclass
class MediaConfig:
    """Media scanning and display configuration.

    This configuration controls how the workflow discovers and presents
    media files for transcription.
    """
    # Directories to scan
    directories: List[str] = field(default_factory=list)

    # File type filters (transcription-specific defaults)
    scan_audio: bool = True
    scan_video: bool = True
    audio_extensions: List[str] = field(default_factory=lambda: [
        "mp3", "wav", "flac", "m4a", "ogg", "wma", "aac"
    ])
    video_extensions: List[str] = field(default_factory=lambda: [
        "mp4", "mkv", "avi", "mov", "webm", "wmv"
    ])

    # Size limits
    min_file_size_kb: int = 0
    max_file_size_mb: int = 0  # 0 = unlimited

    # Scanning behavior
    recursive_scan: bool = True
    include_hidden: bool = False
    follow_symlinks: bool = False
    exclude_patterns: List[str] = field(default_factory=list)

    # Caching
    cache_results: bool = True
    cache_duration_minutes: int = 60

    # Display settings
    max_results: int = 1000
    items_per_page: int = 30
    default_view: str = "list"  # Currently only "list" is implemented
    sort_by: str = "name"  # name, size, modified
    sort_descending: bool = False

# %% ../../nbs/media/config.ipynb 7
MEDIA_CONFIG_SCHEMA = {
    "name": "media",
    "title": "Media Settings",
    "description": "Configure media file scanning and display",
    "type": "object",
    "properties": {
        "directories": {
            "type": "array",
            "title": "Scan Directories",
            "description": "Directories to scan for media files",
            "items": {"type": "string"},
            "default": []
        },
        "scan_audio": {
            "type": "boolean",
            "title": "Scan Audio Files",
            "description": "Include audio files in scan results",
            "default": True
        },
        "scan_video": {
            "type": "boolean",
            "title": "Scan Video Files",
            "description": "Include video files in scan results",
            "default": True
        },
        "audio_extensions": {
            "type": "array",
            "title": "Audio Extensions",
            "description": "File extensions to recognize as audio",
            "items": {"type": "string"},
            "default": ["mp3", "wav", "flac", "m4a", "ogg", "wma", "aac"]
        },
        "video_extensions": {
            "type": "array",
            "title": "Video Extensions",
            "description": "File extensions to recognize as video",
            "items": {"type": "string"},
            "default": ["mp4", "mkv", "avi", "mov", "webm", "wmv"]
        },
        "min_file_size_kb": {
            "type": "integer",
            "title": "Minimum File Size (KB)",
            "description": "Minimum file size in kilobytes (0 = no minimum)",
            "default": 0,
            "minimum": 0
        },
        "max_file_size_mb": {
            "type": "integer",
            "title": "Maximum File Size (MB)",
            "description": "Maximum file size in megabytes (0 = no limit)",
            "default": 0,
            "minimum": 0
        },
        "recursive_scan": {
            "type": "boolean",
            "title": "Recursive Scan",
            "description": "Scan subdirectories",
            "default": True
        },
        "include_hidden": {
            "type": "boolean",
            "title": "Include Hidden Files",
            "description": "Include files starting with a dot",
            "default": False
        },
        "follow_symlinks": {
            "type": "boolean",
            "title": "Follow Symlinks",
            "description": "Follow symbolic links when scanning",
            "default": False
        },
        "exclude_patterns": {
            "type": "array",
            "title": "Exclude Patterns",
            "description": "Glob patterns to exclude from results",
            "items": {"type": "string"},
            "default": []
        },
        "cache_results": {
            "type": "boolean",
            "title": "Cache Results",
            "description": "Cache scan results for faster loading",
            "default": True
        },
        "cache_duration_minutes": {
            "type": "integer",
            "title": "Cache Duration (minutes)",
            "description": "How long to cache scan results",
            "default": 60,
            "minimum": 1
        },
        "items_per_page": {
            "type": "integer",
            "title": "Items Per Page",
            "description": "Number of files to show per page",
            "default": 30,
            "minimum": 10,
            "maximum": 100
        },
        "default_view": {
            "type": "string",
            "title": "Default View",
            "description": "Default view mode for media browser",
            "enum": ["grid", "list"],
            "default": "grid"
        },
        "sort_by": {
            "type": "string",
            "title": "Sort By",
            "description": "Default sort field",
            "enum": ["name", "size", "modified"],
            "default": "name"
        },
        "sort_descending": {
            "type": "boolean",
            "title": "Sort Descending",
            "description": "Sort in descending order",
            "default": False
        }
    }
}
