"""Configuration for transcription result storage"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/storage/config.ipynb.

# %% auto 0
__all__ = ['STORAGE_CONFIG_SCHEMA', 'StorageConfig']

# %% ../../nbs/storage/config.ipynb 3
from dataclasses import dataclass

# %% ../../nbs/storage/config.ipynb 5
@dataclass
class StorageConfig:
    """Result storage configuration."""
    auto_save: bool = True  # Automatically save transcription results when complete
    results_directory: str = "transcription_results"  # Directory to save transcription results

# %% ../../nbs/storage/config.ipynb 7
STORAGE_CONFIG_SCHEMA = {
    "name": "storage",
    "title": "Storage Settings",
    "description": "Configure transcription result storage",
    "type": "object",
    "properties": {
        "auto_save": {
            "type": "boolean",
            "title": "Auto-save Results",
            "description": "Automatically save transcription results when complete",
            "default": True
        },
        "results_directory": {
            "type": "string",
            "title": "Results Directory",
            "description": "Directory to save transcription results",
            "default": "transcription_results"
        }
    }
}
