"""Configuration dataclass for single-file transcription workflow"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/config.ipynb.

# %% auto 0
__all__ = ['DEFAULT_WORKFLOW_CONFIG_DIR', 'SingleFileWorkflowConfig']

# %% ../../nbs/core/config.ipynb 3
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, List

from .html_ids import SingleFileHtmlIds
from ..media.config import MediaConfig
from ..storage.config import StorageConfig

# %% ../../nbs/core/config.ipynb 5
# Default config directory for workflow settings persistence
DEFAULT_WORKFLOW_CONFIG_DIR = Path("configs/workflows/single_file")

# %% ../../nbs/core/config.ipynb 6
@dataclass
class SingleFileWorkflowConfig:
    """Configuration for single-file transcription workflow."""

    # Workflow identification
    workflow_id: str = "single_file_transcription"  # Unique identifier for this workflow
    worker_type: str = "transcription:single_file"  # Worker process type identifier

    # Route configuration
    route_prefix: str = "/single_file"  # Base URL prefix for workflow routes
    stepflow_prefix: str = "/flow"  # Sub-prefix for StepFlow routes
    media_prefix: str = "/media"  # Sub-prefix for media browser routes

    # Container ID for workflow content
    container_id: str = SingleFileHtmlIds.WORKFLOW_CONTAINER  # HTML ID for main workflow container

    # UI options
    show_progress: bool = True  # Show step progress indicator
    max_files_displayed: int = 50  # Maximum files to show in simple file selector

    # Export formats supported
    export_formats: List[str] = field(default_factory=lambda: ["txt", "srt", "vtt"])  # Available export formats

    # Optional navigation URLs
    no_plugins_redirect: Optional[str] = None  # URL to redirect when no plugins configured
    no_files_redirect: Optional[str] = None  # URL to redirect when no media files found

    # SSE polling interval
    sse_poll_interval: float = 2.0  # Seconds between SSE status checks

    # Resource management
    gpu_memory_threshold_percent: float = 45.0  # Max GPU memory % before blocking new jobs

    # Configuration persistence
    config_dir: Path = field(default_factory=lambda: DEFAULT_WORKFLOW_CONFIG_DIR)  # Directory for workflow settings
    plugin_config_dir: Path = field(default_factory=lambda: DEFAULT_WORKFLOW_CONFIG_DIR / "plugins")  # Directory for plugin configs

    # Plugin category
    plugin_category: str = "transcription"  # Plugin category for this workflow

    # Internal subsystem configurations
    media: MediaConfig = field(default_factory=MediaConfig)  # Media scanning and display settings
    storage: StorageConfig = field(default_factory=StorageConfig)  # Result storage settings

    def get_full_stepflow_prefix(self) -> str:  # Combined route_prefix + stepflow_prefix
        """Get the full prefix for the StepFlow router."""
        return f"{self.route_prefix}{self.stepflow_prefix}"

    def get_full_media_prefix(self) -> str:  # Combined route_prefix + media_prefix
        """Get the full prefix for the media router."""
        return f"{self.route_prefix}{self.media_prefix}"
