"""Configuration dataclass for single-file transcription workflow"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/config.ipynb.

# %% auto 0
__all__ = ['DEFAULT_WORKFLOW_CONFIG_DIR', 'SingleFileWorkflowConfig']

# %% ../../nbs/core/config.ipynb 3
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, List

from .html_ids import SingleFileHtmlIds
from ..media.config import MediaConfig
from ..storage.config import StorageConfig

# %% ../../nbs/core/config.ipynb 5
# Default config directory for workflow settings persistence
DEFAULT_WORKFLOW_CONFIG_DIR = Path("configs/workflows/single_file")

# %% ../../nbs/core/config.ipynb 6
@dataclass
class SingleFileWorkflowConfig:
    """Configuration for single-file transcription workflow.

    This configuration allows customization of the workflow behavior
    without modifying the workflow code itself.

    The workflow is fully self-contained with internal subsystems:
    - MediaLibrary (configured via media)
    - ResultStorage (configured via storage)
    - TranscriptionJobManager (created internally)
    - SSEBroadcastManager (created internally)
    """

    # Workflow identification
    workflow_id: str = "single_file_transcription"
    worker_type: str = "transcription:single_file"

    # Route configuration
    # The workflow router will be mounted at route_prefix
    # The StepFlow router will be mounted at route_prefix + stepflow_prefix
    # The media router will be mounted at route_prefix + media_prefix
    route_prefix: str = "/single_file"
    stepflow_prefix: str = "/flow"
    media_prefix: str = "/media"

    # Container ID for workflow content (can override for custom layouts)
    container_id: str = SingleFileHtmlIds.WORKFLOW_CONTAINER

    # UI options
    show_progress: bool = True  # Show step progress indicator
    max_files_displayed: int = 50  # Maximum files to show in simple file selector

    # Export formats supported
    export_formats: List[str] = field(default_factory=lambda: ["txt", "srt", "vtt"])

    # Optional navigation URLs
    # These are used for UI links when dependencies are missing
    # The workflow itself doesn't depend on these routes existing
    no_plugins_redirect: Optional[str] = None  # URL when no plugins configured
    no_files_redirect: Optional[str] = None  # URL when no media files found

    # SSE polling interval in seconds
    sse_poll_interval: float = 2.0

    # Resource management
    gpu_memory_threshold_percent: float = 45.0

    # Configuration persistence directory
    # The workflow saves/loads its settings from this directory
    config_dir: Path = field(default_factory=lambda: DEFAULT_WORKFLOW_CONFIG_DIR)

    # Plugin configuration directory
    # Each workflow has its own plugin configs for isolation
    plugin_config_dir: Path = field(default_factory=lambda: DEFAULT_WORKFLOW_CONFIG_DIR / "plugins")

    # Plugin category for this workflow
    plugin_category: str = "transcription"

    # Internal subsystem configurations
    media: MediaConfig = field(default_factory=MediaConfig)
    storage: StorageConfig = field(default_factory=StorageConfig)

    def get_full_stepflow_prefix(self) -> str:
        """Get the full prefix for the StepFlow router.

        Returns:
            Combined route_prefix + stepflow_prefix.
        """
        return f"{self.route_prefix}{self.stepflow_prefix}"

    def get_full_media_prefix(self) -> str:
        """Get the full prefix for the media router.

        Returns:
            Combined route_prefix + media_prefix.
        """
        return f"{self.route_prefix}{self.media_prefix}"
